# jugadores_data.py
# Generado a partir de SQUAD_REGISTRY de index.bundle.js

jugadores_por_equipo = {
'Real Madrid': [{'numero': '1', 'nombre': 'Thibaut Courtois', 'posicion': 'portero', 'poder': 91},
                {'numero': '13', 'nombre': 'Andriy Lunin', 'posicion': 'portero', 'poder': 84},
                {'numero': '26', 'nombre': 'Fran González', 'posicion': 'portero', 'poder': 68},
                {'numero': '29', 'nombre': 'Javier Navarro', 'posicion': 'portero', 'poder': 66},
                {'numero': '43', 'nombre': 'Sergio Mestre', 'posicion': 'portero', 'poder': 65},
                {'numero': '24', 'nombre': 'Dean Huijsen', 'posicion': 'defensa', 'poder': 85},
                {'numero': '22', 'nombre': 'A. Rüdiger', 'posicion': 'defensa', 'poder': 87},
                {'numero': '12', 'nombre': 'Alexander-Arnold', 'posicion': 'defensa', 'poder': 88},
                {'numero': '18', 'nombre': 'Á. Carreras', 'posicion': 'defensa', 'poder': 83},
                {'numero': '3', 'nombre': 'Éder Militão', 'posicion': 'defensa', 'poder': 86},
                {'numero': '2', 'nombre': 'Dani Carvajal', 'posicion': 'defensa', 'poder': 83},
                {'numero': '17', 'nombre': 'Raúl Asencio', 'posicion': 'defensa', 'poder': 82},
                {'numero': '4', 'nombre': 'David Alaba', 'posicion': 'defensa', 'poder': 81},
                {'numero': '20', 'nombre': 'Fran García', 'posicion': 'defensa', 'poder': 80},
                {'numero': '23', 'nombre': 'Ferland Mendy', 'posicion': 'defensa', 'poder': 83},
                {'numero': '35', 'nombre': 'David Jiménez', 'posicion': 'defensa', 'poder': 68},
                {'numero': '32', 'nombre': 'Jesús Fortea', 'posicion': 'defensa', 'poder': 67},
                {'numero': '40', 'nombre': 'V. Valdepeñas', 'posicion': 'defensa', 'poder': 66},
                {'numero': '27', 'nombre': 'Diego Aguado', 'posicion': 'defensa', 'poder': 65},
                {'numero': '36', 'nombre': 'Joan Martínez', 'posicion': 'defensa', 'poder': 64},
                {'numero': '48', 'nombre': 'L. Fati', 'posicion': 'defensa', 'poder': 64},
                {'numero': '5', 'nombre': 'J. Bellingham', 'posicion': 'medio', 'poder': 90},
                {'numero': '8', 'nombre': 'F. Valverde', 'posicion': 'medio', 'poder': 89},
                {'numero': '14', 'nombre': 'A. Tchouaméni', 'posicion': 'medio', 'poder': 86},
                {'numero': '15', 'nombre': 'Arda Güler', 'posicion': 'medio', 'poder': 85},
                {'numero': '6', 'nombre': 'E. Camavinga', 'posicion': 'medio', 'poder': 86},
                {'numero': '19', 'nombre': 'Dani Ceballos', 'posicion': 'medio', 'poder': 80},
                {'numero': '45', 'nombre': 'T. Pitarch', 'posicion': 'medio', 'poder': 72},
                {'numero': '37', 'nombre': 'Manuel Ángel', 'posicion': 'medio', 'poder': 69},
                {'numero': '38', 'nombre': 'César Palacios', 'posicion': 'medio', 'poder': 68},
                {'numero': '46', 'nombre': 'Álvaro Leiva', 'posicion': 'medio', 'poder': 66},
                {'numero': '28', 'nombre': 'Jorge Cestero', 'posicion': 'medio', 'poder': 66},
                {'numero': '47', 'nombre': 'Dani Mesonero', 'posicion': 'medio', 'poder': 65},
                {'numero': '10', 'nombre': 'K. Mbappé', 'posicion': 'delantero', 'poder': 92},
                {'numero': '7', 'nombre': 'Vinícius', 'posicion': 'delantero', 'poder': 90},
                {'numero': '11', 'nombre': 'Rodrygo', 'posicion': 'delantero', 'poder': 85},
                {'numero': '30', 'nombre': 'F. Mastantuono', 'posicion': 'delantero', 'poder': 80},
                {'numero': '21', 'nombre': 'Brahim Díaz', 'posicion': 'delantero', 'poder': 83},
                {'numero': '16', 'nombre': 'Gonzalo García', 'posicion': 'delantero', 'poder': 78},
                {'numero': '42', 'nombre': 'Daniel Yáñez', 'posicion': 'delantero', 'poder': 66}],
 'FC Barcelona': [{'numero': '13', 'nombre': 'Joan García', 'posicion': 'portero', 'poder': 85},
                 {'numero': '25', 'nombre': 'W. Szczęsny', 'posicion': 'portero', 'poder': 83},
                 {'numero': '31', 'nombre': 'D. Kochen', 'posicion': 'portero', 'poder': 68},
                 {'numero': '33', 'nombre': 'Eder Aller', 'posicion': 'portero', 'poder': 65},
                 {'numero': '23', 'nombre': 'Jules Koundé', 'posicion': 'defensa', 'poder': 86},
                 {'numero': '2', 'nombre': 'João Cancelo', 'posicion': 'defensa', 'poder': 85},
                 {'numero': '3', 'nombre': 'Álex Balde', 'posicion': 'defensa', 'poder': 84},
                 {'numero': '5', 'nombre': 'Pau Cubarsí', 'posicion': 'defensa', 'poder': 84},
                 {'numero': '24', 'nombre': 'Eric García', 'posicion': 'defensa', 'poder': 83},
                 {'numero': '4', 'nombre': 'Ronald Araujo', 'posicion': 'defensa', 'poder': 87},
                 {'numero': '15', 'nombre': 'A. Christensen', 'posicion': 'defensa', 'poder': 82},
                 {'numero': '18', 'nombre': 'Gerard Martín', 'posicion': 'defensa', 'poder': 80},
                 {'numero': '36', 'nombre': 'Á. Cortés', 'posicion': 'defensa', 'poder': 70},
                 {'numero': '42', 'nombre': 'Xavi Espart', 'posicion': 'defensa', 'poder': 68},
                 {'numero': '26', 'nombre': 'Jofre Torrents', 'posicion': 'defensa', 'poder': 67},
                 {'numero': '8', 'nombre': 'Pedri', 'posicion': 'medio', 'poder': 88},
                 {'numero': '21', 'nombre': 'F. De Jong', 'posicion': 'medio', 'poder': 87},
                 {'numero': '20', 'nombre': 'Dani Olmo', 'posicion': 'medio', 'poder': 86},
                 {'numero': '16', 'nombre': 'Fermín López', 'posicion': 'medio', 'poder': 85},
                 {'numero': '6', 'nombre': 'Gavi', 'posicion': 'medio', 'poder': 86},
                 {'numero': '17', 'nombre': 'Marc Casadó', 'posicion': 'medio', 'poder': 78},
                 {'numero': '22', 'nombre': 'Marc Bernal', 'posicion': 'medio', 'poder': 77},
                 {'numero': '30', 'nombre': 'Guille Fernández', 'posicion': 'medio', 'poder': 70},
                 {'numero': '29', 'nombre': 'Toni Fernández', 'posicion': 'medio', 'poder': 69},
                 {'numero': '41', 'nombre': 'J. Hernández', 'posicion': 'medio', 'poder': 68},
                 {'numero': '43', 'nombre': 'Tommy Marqués', 'posicion': 'medio', 'poder': 67},
                 {'numero': '11', 'nombre': 'Raphinha', 'posicion': 'delantero', 'poder': 88},
                 {'numero': '10', 'nombre': 'Lamine Yamal', 'posicion': 'delantero', 'poder': 90},
                 {'numero': '14', 'nombre': 'M. Rashford', 'posicion': 'delantero', 'poder': 87},
                 {'numero': '9', 'nombre': 'R. Lewandowski', 'posicion': 'delantero', 'poder': 88},
                 {'numero': '7', 'nombre': 'Ferran Torres', 'posicion': 'delantero', 'poder': 86},
                 {'numero': '19', 'nombre': 'R. Bardghji', 'posicion': 'delantero', 'poder': 79}],
 'Athletic Club': [{'numero': '1', 'nombre': 'Unai Simón', 'posicion': 'portero', 'poder': 88},
                  {'numero': '26', 'nombre': 'Mikel Santos', 'posicion': 'portero', 'poder': 67},
                  {'numero': '27', 'nombre': 'Álex Padilla', 'posicion': 'portero', 'poder': 66},
                  {'numero': '3', 'nombre': 'Dani Vivian', 'posicion': 'defensa', 'poder': 83},
                  {'numero': '17', 'nombre': 'Yuri', 'posicion': 'defensa', 'poder': 84},
                  {'numero': '14', 'nombre': 'A. Laporte', 'posicion': 'defensa', 'poder': 86},
                  {'numero': '4', 'nombre': 'Aitor Paredes', 'posicion': 'defensa', 'poder': 81},
                  {'numero': '12', 'nombre': 'Jesús Areso', 'posicion': 'defensa', 'poder': 80},
                  {'numero': '2', 'nombre': 'A. Gorosabel', 'posicion': 'defensa', 'poder': 80},
                  {'numero': '5', 'nombre': 'Yeray', 'posicion': 'defensa', 'poder': 80},
                  {'numero': '15', 'nombre': 'Iñigo Lekue', 'posicion': 'defensa', 'poder': 79},
                  {'numero': '19', 'nombre': 'Adama Boiro', 'posicion': 'defensa', 'poder': 77},
                  {'numero': '34', 'nombre': 'Jon De Luis', 'posicion': 'defensa', 'poder': 65},
                  {'numero': '47', 'nombre': 'I. Monreal', 'posicion': 'defensa', 'poder': 65},
                  {'numero': '8', 'nombre': 'Oihan Sancet', 'posicion': 'medio', 'poder': 85},
                  {'numero': '18', 'nombre': 'M. Jauregizar', 'posicion': 'medio', 'poder': 82},
                  {'numero': '16', 'nombre': 'I. Ruiz De Galarreta', 'posicion': 'medio', 'poder': 83},
                  {'numero': '20', 'nombre': 'Unai Gómez', 'posicion': 'medio', 'poder': 80},
                  {'numero': '30', 'nombre': 'Rego', 'posicion': 'medio', 'poder': 79},
                  {'numero': '6', 'nombre': 'Mikel Vesga', 'posicion': 'medio', 'poder': 79},
                  {'numero': '24', 'nombre': 'Beñat Prados', 'posicion': 'medio', 'poder': 75},
                  {'numero': '44', 'nombre': 'Selton Sued', 'posicion': 'medio', 'poder': 74},
                  {'numero': '35', 'nombre': 'Ibon Sánchez', 'posicion': 'medio', 'poder': 65},
                  {'numero': '49', 'nombre': 'Eder García', 'posicion': 'medio', 'poder': 66},
                  {'numero': '11', 'nombre': 'G. Guruzeta', 'posicion': 'delantero', 'poder': 84},
                  {'numero': '10', 'nombre': 'Nico Williams', 'posicion': 'delantero', 'poder': 86},
                  {'numero': '9', 'nombre': 'I. Williams', 'posicion': 'delantero', 'poder': 85},
                  {'numero': '7', 'nombre': 'Álex Berenguer', 'posicion': 'delantero', 'poder': 83},
                  {'numero': '23', 'nombre': 'Robert Navarro', 'posicion': 'delantero', 'poder': 80},
                  {'numero': '22', 'nombre': 'Nico Serrano', 'posicion': 'delantero', 'poder': 78},
                  {'numero': '21', 'nombre': 'M. Sannadi', 'posicion': 'delantero', 'poder': 76},
                  {'numero': '25', 'nombre': 'Izeta', 'posicion': 'delantero', 'poder': 72},
                  {'numero': '48', 'nombre': 'E. Buján', 'posicion': 'delantero', 'poder': 65},
                  {'numero': '31', 'nombre': 'Asier Hierro', 'posicion': 'delantero', 'poder': 65}],
 'Atletico Madrid': [{'numero': '13', 'nombre': 'Jan Oblak', 'posicion': 'portero', 'poder': 90},
                    {'numero': '1', 'nombre': 'J. Musso', 'posicion': 'portero', 'poder': 83},
                    {'numero': '31', 'nombre': 'S. Esquivel', 'posicion': 'portero', 'poder': 68},
                    {'numero': '51', 'nombre': 'Álvaro Moreno', 'posicion': 'portero', 'poder': 66},
                    {'numero': '33', 'nombre': 'Mario De Luis', 'posicion': 'portero', 'poder': 65},
                    {'numero': '17', 'nombre': 'Dávid Hancko', 'posicion': 'defensa', 'poder': 85},
                    {'numero': '14', 'nombre': 'M. Llorente', 'posicion': 'defensa', 'poder': 86},
                    {'numero': '24', 'nombre': 'R. Le Normand', 'posicion': 'defensa', 'poder': 84},
                    {'numero': '2', 'nombre': 'J. Giménez', 'posicion': 'defensa', 'poder': 84},
                    {'numero': '16', 'nombre': 'Nahuel Molina', 'posicion': 'defensa', 'poder': 83},
                    {'numero': '18', 'nombre': 'Marc Pubill', 'posicion': 'defensa', 'poder': 85},
                    {'numero': '15', 'nombre': 'C. Lenglet', 'posicion': 'defensa', 'poder': 82},
                    {'numero': '3', 'nombre': 'Matteo Ruggeri', 'posicion': 'defensa', 'poder': 81},
                    {'numero': '32', 'nombre': 'Javier Boñar', 'posicion': 'defensa', 'poder': 72},
                    {'numero': '40', 'nombre': 'Aleksa Purić', 'posicion': 'defensa', 'poder': 66},
                    {'numero': '26', 'nombre': 'Ilias Kostis', 'posicion': 'defensa', 'poder': 65},
                    {'numero': '34', 'nombre': 'Julio Díaz', 'posicion': 'defensa', 'poder': 70},
                    {'numero': '30', 'nombre': 'Dani Martínez', 'posicion': 'defensa', 'poder': 68},
                    {'numero': '36', 'nombre': 'Gero Spina', 'posicion': 'defensa', 'poder': 64},
                    {'numero': '6', 'nombre': 'Koke', 'posicion': 'medio', 'poder': 85},
                    {'numero': '7', 'nombre': 'A. Griezmann', 'posicion': 'medio', 'poder': 88},
                    {'numero': '8', 'nombre': 'Pablo Barrios', 'posicion': 'medio', 'poder': 82},
                    {'numero': '5', 'nombre': 'Johnny Cardoso', 'posicion': 'medio', 'poder': 81},
                    {'numero': '21', 'nombre': 'Obed Vargas', 'posicion': 'medio', 'poder': 79},
                    {'numero': '29', 'nombre': 'Rayane Belaid', 'posicion': 'medio', 'poder': 70},
                    {'numero': '4', 'nombre': 'Rodrigo Mendoza', 'posicion': 'medio', 'poder': 72},
                    {'numero': '42', 'nombre': 'Javi Serrano', 'posicion': 'medio', 'poder': 68},
                    {'numero': '27', 'nombre': 'Jano Monserrate', 'posicion': 'medio', 'poder': 66},
                    {'numero': '47', 'nombre': 'Javi Morcillo', 'posicion': 'medio', 'poder': 69},
                    {'numero': '28', 'nombre': 'Taufik Seidu', 'posicion': 'medio', 'poder': 65},
                    {'numero': '9', 'nombre': 'A. Sørloth', 'posicion': 'delantero', 'poder': 86},
                    {'numero': '19', 'nombre': 'Julián Alvarez', 'posicion': 'delantero', 'poder': 87},
                    {'numero': '23', 'nombre': 'Nico González', 'posicion': 'delantero', 'poder': 82},
                    {'numero': '10', 'nombre': 'Álex Baena', 'posicion': 'delantero', 'poder': 84},
                    {'numero': '11', 'nombre': 'T. Almada', 'posicion': 'delantero', 'poder': 83},
                    {'numero': '22', 'nombre': 'A. Lookman', 'posicion': 'delantero', 'poder': 82},
                    {'numero': '20', 'nombre': 'Giuliano', 'posicion': 'delantero', 'poder': 81},
                    {'numero': '37', 'nombre': 'Iker Luque', 'posicion': 'delantero', 'poder': 68},
                    {'numero': '45', 'nombre': 'S. Esteban', 'posicion': 'delantero', 'poder': 65},
                    {'numero': '61', 'nombre': 'Miguel Cubo', 'posicion': 'delantero', 'poder': 66}],
 'Betis': [{'numero': '1', 'nombre': 'Álvaro Valles', 'posicion': 'portero', 'poder': 84},
          {'numero': '25', 'nombre': 'Pau López', 'posicion': 'portero', 'poder': 82},
          {'numero': '13', 'nombre': 'Adrián', 'posicion': 'portero', 'poder': 78},
          {'numero': '41', 'nombre': 'Manu González', 'posicion': 'portero', 'poder': 66},
          {'numero': '30', 'nombre': 'Germán García', 'posicion': 'portero', 'poder': 65},
          {'numero': '4', 'nombre': 'Natan', 'posicion': 'defensa', 'poder': 82},
          {'numero': '12', 'nombre': 'Ricardo Rodríguez', 'posicion': 'defensa', 'poder': 81},
          {'numero': '5', 'nombre': 'Marc Bartra', 'posicion': 'defensa', 'poder': 83},
          {'numero': '3', 'nombre': 'Diego Llorente', 'posicion': 'defensa', 'poder': 82},
          {'numero': '16', 'nombre': 'Valentín Gómez', 'posicion': 'defensa', 'poder': 82},
          {'numero': '23', 'nombre': 'Junior Firpo', 'posicion': 'defensa', 'poder': 80},
          {'numero': '2', 'nombre': 'Héctor Bellerín', 'posicion': 'defensa', 'poder': 81},
          {'numero': '40', 'nombre': 'Ángel Ortiz', 'posicion': 'defensa', 'poder': 74},
          {'numero': '36', 'nombre': 'Darling Bladi', 'posicion': 'defensa', 'poder': 66},
          {'numero': '42', 'nombre': 'Pablo Busto', 'posicion': 'defensa', 'poder': 65},
          {'numero': '33', 'nombre': 'C. De Roa', 'posicion': 'defensa', 'poder': 65},
          {'numero': '22', 'nombre': 'Isco', 'posicion': 'medio', 'poder': 86},
          {'numero': '8', 'nombre': 'Pablo Fornals', 'posicion': 'medio', 'poder': 85},
          {'numero': '15', 'nombre': 'Á. Fidalgo', 'posicion': 'medio', 'poder': 79},
          {'numero': '18', 'nombre': 'N. Deossa', 'posicion': 'medio', 'poder': 78},
          {'numero': '14', 'nombre': 'S. Amrabat', 'posicion': 'medio', 'poder': 83},
          {'numero': '20', 'nombre': 'G. Lo Celso', 'posicion': 'medio', 'poder': 84},
          {'numero': '21', 'nombre': 'Marc Roca', 'posicion': 'medio', 'poder': 82},
          {'numero': '6', 'nombre': 'Sergi Altimira', 'posicion': 'medio', 'poder': 80},
          {'numero': '37', 'nombre': 'Dani Pérez', 'posicion': 'medio', 'poder': 66},
          {'numero': '50', 'nombre': 'Iván Corralejo', 'posicion': 'medio', 'poder': 65},
          {'numero': '19', 'nombre': 'Cucho', 'posicion': 'delantero', 'poder': 84},
          {'numero': '10', 'nombre': 'Ez Abde', 'posicion': 'delantero', 'poder': 83},
          {'numero': '7', 'nombre': 'Antony', 'posicion': 'delantero', 'poder': 85},
          {'numero': '11', 'nombre': 'C. Bakambu', 'posicion': 'delantero', 'poder': 79},
          {'numero': '24', 'nombre': 'Aitor Ruibal', 'posicion': 'delantero', 'poder': 80},
          {'numero': '17', 'nombre': 'R. Riquelme', 'posicion': 'delantero', 'poder': 78},
          {'numero': '9', 'nombre': 'Chimy Ávila', 'posicion': 'delantero', 'poder': 77},
          {'numero': '52', 'nombre': 'Pablo García', 'posicion': 'delantero', 'poder': 70},
          {'numero': '29', 'nombre': 'Rodrigo Marina', 'posicion': 'delantero', 'poder': 65}],
 'Real Sociedad': [{'numero': '1', 'nombre': 'Álex Remiro', 'posicion': 'portero', 'poder': 86},
                  {'numero': '32', 'nombre': 'Aitor Fraga', 'posicion': 'portero', 'poder': 68},
                  {'numero': '13', 'nombre': 'Unai Marrero', 'posicion': 'portero', 'poder': 67},
                  {'numero': '41', 'nombre': 'Theo Folgado', 'posicion': 'portero', 'poder': 66},
                  {'numero': '2', 'nombre': 'Jon Aramburu', 'posicion': 'defensa', 'poder': 82},
                  {'numero': '5', 'nombre': 'Igor Zubeldia', 'posicion': 'defensa', 'poder': 83},
                  {'numero': '16', 'nombre': 'D. Ćaleta-Car', 'posicion': 'defensa', 'poder': 82},
                  {'numero': '17', 'nombre': 'Sergio Gómez', 'posicion': 'defensa', 'poder': 83},
                  {'numero': '31', 'nombre': 'Jon Martín', 'posicion': 'defensa', 'poder': 80},
                  {'numero': '3', 'nombre': 'Aihen Muñoz', 'posicion': 'defensa', 'poder': 80},
                  {'numero': '6', 'nombre': 'A. Elustondo', 'posicion': 'defensa', 'poder': 81},
                  {'numero': '20', 'nombre': 'Á. Odriozola', 'posicion': 'defensa', 'poder': 79},
                  {'numero': '38', 'nombre': 'Luken Beitia', 'posicion': 'defensa', 'poder': 68},
                  {'numero': '45', 'nombre': 'Kazunari Kita', 'posicion': 'defensa', 'poder': 66},
                  {'numero': '23', 'nombre': 'Brais Méndez', 'posicion': 'medio', 'poder': 85},
                  {'numero': '4', 'nombre': 'J. Gorrotxategi', 'posicion': 'medio', 'poder': 82},
                  {'numero': '24', 'nombre': 'Luka Sučić', 'posicion': 'medio', 'poder': 81},
                  {'numero': '18', 'nombre': 'Carlos Soler', 'posicion': 'medio', 'poder': 84},
                  {'numero': '15', 'nombre': 'Pablo Marín', 'posicion': 'medio', 'poder': 80},
                  {'numero': '8', 'nombre': 'B. Turrientes', 'posicion': 'medio', 'poder': 81},
                  {'numero': '12', 'nombre': 'Y. Herrera', 'posicion': 'medio', 'poder': 77},
                  {'numero': '21', 'nombre': 'A. Zakharyan', 'posicion': 'medio', 'poder': 80},
                  {'numero': '43', 'nombre': 'T. Carbonell', 'posicion': 'medio', 'poder': 66},
                  {'numero': '36', 'nombre': 'Alex Lebarbier', 'posicion': 'medio', 'poder': 65},
                  {'numero': '46', 'nombre': 'I. Aguirre', 'posicion': 'medio', 'poder': 66},
                  {'numero': '10', 'nombre': 'M. Oyarzabal', 'posicion': 'delantero', 'poder': 88},
                  {'numero': '11', 'nombre': 'G. Guedes', 'posicion': 'delantero', 'poder': 84},
                  {'numero': '14', 'nombre': 'Take Kubo', 'posicion': 'delantero', 'poder': 85},
                  {'numero': '7', 'nombre': 'A. Barrenetxea', 'posicion': 'delantero', 'poder': 83},
                  {'numero': '9', 'nombre': 'O. Óskarsson', 'posicion': 'delantero', 'poder': 81},
                  {'numero': '22', 'nombre': 'Wesley', 'posicion': 'delantero', 'poder': 74},
                  {'numero': '42', 'nombre': 'Gorka Carrera', 'posicion': 'delantero', 'poder': 68},
                  {'numero': '19', 'nombre': 'J. Karrikaburu', 'posicion': 'delantero', 'poder': 75},
                  {'numero': '47', 'nombre': 'Job Ochieng', 'posicion': 'delantero', 'poder': 66},
                  {'numero': '44', 'nombre': 'L. Astiazarán', 'posicion': 'delantero', 'poder': 66},
                  {'numero': '34', 'nombre': 'A. Mariezkurrena', 'posicion': 'delantero', 'poder': 67},
                  {'numero': '40', 'nombre': 'Alex Marchal', 'posicion': 'delantero', 'poder': 65},
                  {'numero': '26', 'nombre': 'Dani Díaz', 'posicion': 'delantero', 'poder': 66}],
 'Sevilla': [{'numero': '1', 'nombre': 'O. Vlachodimos', 'posicion': 'portero', 'poder': 85},
            {'numero': '13', 'nombre': 'Ø. Nyland', 'posicion': 'portero', 'poder': 80},
            {'numero': '31', 'nombre': 'Alberto Flores', 'posicion': 'portero', 'poder': 66},
            {'numero': '33', 'nombre': 'Rafa Romero', 'posicion': 'portero', 'poder': 65},
            {'numero': '40', 'nombre': 'Loren Luchino', 'posicion': 'portero', 'poder': 65},
            {'numero': '12', 'nombre': 'Gabriel Suazo', 'posicion': 'defensa', 'poder': 82},
            {'numero': '3', 'nombre': 'C. Azpilicueta', 'posicion': 'defensa', 'poder': 84},
            {'numero': '4', 'nombre': 'Kike Salas', 'posicion': 'defensa', 'poder': 81},
            {'numero': '2', 'nombre': 'Carmona', 'posicion': 'defensa', 'poder': 82},
            {'numero': '16', 'nombre': 'Juanlu Sánchez', 'posicion': 'defensa', 'poder': 81},
            {'numero': '23', 'nombre': 'Marcão', 'posicion': 'defensa', 'poder': 80},
            {'numero': '5', 'nombre': 'T. Nianzou', 'posicion': 'defensa', 'poder': 79},
            {'numero': '32', 'nombre': 'Andrés Castrín', 'posicion': 'defensa', 'poder': 78},
            {'numero': '36', 'nombre': 'Oso', 'posicion': 'defensa', 'poder': 79},
            {'numero': '15', 'nombre': 'Fábio Cardoso', 'posicion': 'defensa', 'poder': 75},
            {'numero': '41', 'nombre': 'Iker Muñoz', 'posicion': 'defensa', 'poder': 65},
            {'numero': '22', 'nombre': 'F. Gattoni', 'posicion': 'defensa', 'poder': 66},
            {'numero': '6', 'nombre': 'N. Gudelj', 'posicion': 'medio', 'poder': 83},
            {'numero': '20', 'nombre': 'Djibril Sow', 'posicion': 'medio', 'poder': 84},
            {'numero': '10', 'nombre': 'Alexis Sánchez', 'posicion': 'medio', 'poder': 85},
            {'numero': '18', 'nombre': 'L. Agoumé', 'posicion': 'medio', 'poder': 82},
            {'numero': '19', 'nombre': 'B. Mendy', 'posicion': 'medio', 'poder': 80},
            {'numero': '14', 'nombre': 'Peque', 'posicion': 'medio', 'poder': 79},
            {'numero': '8', 'nombre': 'Joan Jordán', 'posicion': 'medio', 'poder': 78},
            {'numero': '28', 'nombre': 'Manu Bueno', 'posicion': 'medio', 'poder': 72},
            {'numero': '38', 'nombre': 'Nico Guillén', 'posicion': 'medio', 'poder': 65},
            {'numero': '39', 'nombre': 'Edu Altozano', 'posicion': 'medio', 'poder': 65},
            {'numero': '9', 'nombre': 'Akor Adams', 'posicion': 'delantero', 'poder': 84},
            {'numero': '11', 'nombre': 'Rubén Vargas', 'posicion': 'delantero', 'poder': 83},
            {'numero': '7', 'nombre': 'Isaac Romero', 'posicion': 'delantero', 'poder': 82},
            {'numero': '17', 'nombre': 'Neal Maupay', 'posicion': 'delantero', 'poder': 80},
            {'numero': '21', 'nombre': 'C. Ejuke', 'posicion': 'delantero', 'poder': 78},
            {'numero': '24', 'nombre': 'Adnan Januzaj', 'posicion': 'delantero', 'poder': 79},
            {'numero': '29', 'nombre': 'Miguel Sierra', 'posicion': 'delantero', 'poder': 66},
            {'numero': '26', 'nombre': 'Álex Costa', 'posicion': 'delantero', 'poder': 65}],
 'Villarreal': [{'numero': '1', 'nombre': 'Luiz Júnior', 'posicion': 'portero', 'poder': 84},
               {'numero': '25', 'nombre': 'Arnau Tenas', 'posicion': 'portero', 'poder': 82},
               {'numero': '13', 'nombre': 'Diego Conde', 'posicion': 'portero', 'poder': 68},
               {'numero': '31', 'nombre': 'Rubén Gómez', 'posicion': 'portero', 'poder': 66},
               {'numero': '23', 'nombre': 'Sergi Cardona', 'posicion': 'defensa', 'poder': 82},
               {'numero': '12', 'nombre': 'Renato Veiga', 'posicion': 'defensa', 'poder': 83},
               {'numero': '8', 'nombre': 'Juan Foyth', 'posicion': 'defensa', 'poder': 84},
               {'numero': '15', 'nombre': 'S. Mouriño', 'posicion': 'defensa', 'poder': 81},
               {'numero': '4', 'nombre': 'Rafa Marín', 'posicion': 'defensa', 'poder': 80},
               {'numero': '24', 'nombre': 'A. Pedraza', 'posicion': 'defensa', 'poder': 82},
               {'numero': '6', 'nombre': 'Pau Navarro', 'posicion': 'defensa', 'poder': 79},
               {'numero': '3', 'nombre': 'Alex Freeman', 'posicion': 'defensa', 'poder': 74},
               {'numero': '2', 'nombre': 'Logan Costa', 'posicion': 'defensa', 'poder': 70},
               {'numero': '5', 'nombre': 'W. Kambwala', 'posicion': 'defensa', 'poder': 69},
               {'numero': '29', 'nombre': 'Sierra', 'posicion': 'defensa', 'poder': 65},
               {'numero': '27', 'nombre': 'Ives Valou', 'posicion': 'defensa', 'poder': 64},
               {'numero': '14', 'nombre': 'Santi Comesaña', 'posicion': 'medio', 'poder': 84},
               {'numero': '18', 'nombre': 'Pape Gueye', 'posicion': 'medio', 'poder': 83},
               {'numero': '10', 'nombre': 'Dani Parejo', 'posicion': 'medio', 'poder': 85},
               {'numero': '16', 'nombre': 'Thomas', 'posicion': 'medio', 'poder': 80},
               {'numero': '37', 'nombre': 'Carlos Maciá', 'posicion': 'medio', 'poder': 70},
               {'numero': '38', 'nombre': 'Alassane', 'posicion': 'medio', 'poder': 66},
               {'numero': '9', 'nombre': 'G. Mikautadze', 'posicion': 'delantero', 'poder': 85},
               {'numero': '20', 'nombre': 'A. Moleiro', 'posicion': 'delantero', 'poder': 85},
               {'numero': '7', 'nombre': 'Gerard Moreno', 'posicion': 'delantero', 'poder': 85},
               {'numero': '19', 'nombre': 'Nicolas Pépé', 'posicion': 'delantero', 'poder': 83},
               {'numero': '17', 'nombre': 'T. Buchanan', 'posicion': 'delantero', 'poder': 82},
               {'numero': '22', 'nombre': 'Ayoze', 'posicion': 'delantero', 'poder': 81},
               {'numero': '21', 'nombre': 'Tani Oluwaseyi', 'posicion': 'delantero', 'poder': 78},
               {'numero': '11', 'nombre': 'Alfon González', 'posicion': 'delantero', 'poder': 72},
               {'numero': '32', 'nombre': 'Hugo López', 'posicion': 'delantero', 'poder': 68},
               {'numero': '33', 'nombre': 'Pau Cabanes', 'posicion': 'delantero', 'poder': 66},
               {'numero': '40', 'nombre': 'Joselillo Gaitán', 'posicion': 'delantero', 'poder': 65},
               {'numero': '28', 'nombre': 'M. Barry', 'posicion': 'delantero', 'poder': 64}],
 'Espanyol': [{'numero': '13', 'nombre': 'M. Dmitrović', 'posicion': 'portero', 'poder': 84},
             {'numero': '1', 'nombre': 'Ángel Fortuño', 'posicion': 'portero', 'poder': 68},
             {'numero': '31', 'nombre': 'L. Serred', 'posicion': 'portero', 'poder': 66},
             {'numero': '30', 'nombre': 'Pol Tristán', 'posicion': 'portero', 'poder': 65},
             {'numero': '6', 'nombre': 'L. Cabrera', 'posicion': 'defensa', 'poder': 85},
             {'numero': '22', 'nombre': 'Carlos Romero', 'posicion': 'defensa', 'poder': 82},
             {'numero': '23', 'nombre': 'Omar El Hilali', 'posicion': 'defensa', 'poder': 81},
             {'numero': '5', 'nombre': 'F. Calero', 'posicion': 'defensa', 'poder': 81},
             {'numero': '38', 'nombre': 'C. Riedel', 'posicion': 'defensa', 'poder': 80},
             {'numero': '2', 'nombre': 'Rubén Sánchez', 'posicion': 'defensa', 'poder': 78},
             {'numero': '15', 'nombre': 'Miguel Rubio', 'posicion': 'defensa', 'poder': 76},
             {'numero': '12', 'nombre': 'J. Salinas', 'posicion': 'defensa', 'poder': 75},
             {'numero': '27', 'nombre': 'A. Timera', 'posicion': 'defensa', 'poder': 65},
             {'numero': '8', 'nombre': 'Edu Expósito', 'posicion': 'medio', 'poder': 83},
             {'numero': '10', 'nombre': 'Pol Lozano', 'posicion': 'medio', 'poder': 82},
             {'numero': '4', 'nombre': 'Urko González', 'posicion': 'medio', 'poder': 81},
             {'numero': '18', 'nombre': 'C. Pickel', 'posicion': 'medio', 'poder': 78},
             {'numero': '14', 'nombre': 'Ramón Terrats', 'posicion': 'medio', 'poder': 80},
             {'numero': '28', 'nombre': 'F. Gómez', 'posicion': 'medio', 'poder': 65},
             {'numero': '26', 'nombre': 'M. Londoño', 'posicion': 'medio', 'poder': 65},
             {'numero': '9', 'nombre': 'Roberto', 'posicion': 'delantero', 'poder': 82},
             {'numero': '11', 'nombre': 'Pere Milla', 'posicion': 'delantero', 'poder': 83},
             {'numero': '24', 'nombre': 'Tyrhys Dolan', 'posicion': 'delantero', 'poder': 81},
             {'numero': '19', 'nombre': 'Kike García', 'posicion': 'delantero', 'poder': 83},
             {'numero': '7', 'nombre': 'Javi Puado', 'posicion': 'delantero', 'poder': 80},
             {'numero': '17', 'nombre': 'Jofre', 'posicion': 'delantero', 'poder': 78},
             {'numero': '16', 'nombre': 'Cyril Ngonge', 'posicion': 'delantero', 'poder': 79},
             {'numero': '20', 'nombre': 'Antoniu', 'posicion': 'delantero', 'poder': 74},
             {'numero': '33', 'nombre': 'A. Almansa', 'posicion': 'delantero', 'poder': 65},
             {'numero': '32', 'nombre': 'Lluc Castell', 'posicion': 'delantero', 'poder': 65}],
 'Getafe': [{'numero': '13', 'nombre': 'David Soria', 'posicion': 'portero', 'poder': 83},
           {'numero': '1', 'nombre': 'Jiří Letáček', 'posicion': 'portero', 'poder': 68},
           {'numero': '35', 'nombre': 'Jorge Benito', 'posicion': 'portero', 'poder': 66},
           {'numero': '42', 'nombre': 'D. Ferrer', 'posicion': 'portero', 'poder': 65},
           {'numero': '16', 'nombre': 'Diego Rico', 'posicion': 'defensa', 'poder': 80},
           {'numero': '2', 'nombre': 'D. Djené', 'posicion': 'defensa', 'poder': 82},
           {'numero': '21', 'nombre': 'Juan Iglesias', 'posicion': 'defensa', 'poder': 81},
           {'numero': '17', 'nombre': 'Kiko Femenía', 'posicion': 'defensa', 'poder': 80},
           {'numero': '22', 'nombre': 'D. Duarte', 'posicion': 'defensa', 'poder': 81},
           {'numero': '3', 'nombre': 'A. Abqar', 'posicion': 'defensa', 'poder': 80},
           {'numero': '24', 'nombre': 'Zaid Romero', 'posicion': 'defensa', 'poder': 78},
           {'numero': '15', 'nombre': 'S. Boselli', 'posicion': 'defensa', 'poder': 76},
           {'numero': '26', 'nombre': 'Davinchi', 'posicion': 'defensa', 'poder': 74},
           {'numero': '12', 'nombre': 'A. Nyom', 'posicion': 'defensa', 'poder': 77},
           {'numero': '32', 'nombre': 'L. Laso', 'posicion': 'defensa', 'poder': 66},
           {'numero': '31', 'nombre': 'Ismael Bekhoucha', 'posicion': 'defensa', 'poder': 70},
           {'numero': '33', 'nombre': 'M. Vilaplana', 'posicion': 'defensa', 'poder': 65},
           {'numero': '41', 'nombre': 'Jorge Montes', 'posicion': 'defensa', 'poder': 64},
           {'numero': '5', 'nombre': 'Luis Milla', 'posicion': 'medio', 'poder': 82},
           {'numero': '8', 'nombre': 'M. Arambarri', 'posicion': 'medio', 'poder': 83},
           {'numero': '14', 'nombre': 'Javi Muñoz', 'posicion': 'medio', 'poder': 76},
           {'numero': '6', 'nombre': 'Mario Martín', 'posicion': 'medio', 'poder': 80},
           {'numero': '34', 'nombre': 'H. Solozábal', 'posicion': 'medio', 'poder': 66},
           {'numero': '45', 'nombre': 'A. Mestanza', 'posicion': 'medio', 'poder': 68},
           {'numero': '44', 'nombre': 'A. Riquelme', 'posicion': 'medio', 'poder': 65},
           {'numero': '46', 'nombre': 'Damián Cáceres', 'posicion': 'medio', 'poder': 67},
           {'numero': '30', 'nombre': 'Alberto Risco', 'posicion': 'medio', 'poder': 65},
           {'numero': '10', 'nombre': 'Martín Satriano', 'posicion': 'delantero', 'poder': 81},
           {'numero': '9', 'nombre': 'B. Mayoral', 'posicion': 'delantero', 'poder': 80},
           {'numero': '19', 'nombre': 'Luis Vázquez', 'posicion': 'delantero', 'poder': 79},
           {'numero': '23', 'nombre': 'Adrián Liso', 'posicion': 'delantero', 'poder': 78},
           {'numero': '20', 'nombre': 'V. Birmančević', 'posicion': 'delantero', 'poder': 75},
           {'numero': '11', 'nombre': 'Abu Kamara', 'posicion': 'delantero', 'poder': 74},
           {'numero': '18', 'nombre': 'Álex Sancris', 'posicion': 'delantero', 'poder': 76},
           {'numero': '7', 'nombre': 'Juanmi', 'posicion': 'delantero', 'poder': 77},
           {'numero': '37', 'nombre': 'Joselu', 'posicion': 'delantero', 'poder': 72},
           {'numero': '39', 'nombre': 'Yassin Tallal', 'posicion': 'delantero', 'poder': 65},
           {'numero': '29', 'nombre': 'Mykyta', 'posicion': 'delantero', 'poder': 65}],
 'Albacete BP': [{'numero': '1', 'nombre': 'Mariño', 'posicion': 'portero', 'poder': 67},
                {'numero': '13', 'nombre': 'Lizoain', 'posicion': 'portero', 'poder': 69},
                {'numero': '25', 'nombre': 'M. Ramos', 'posicion': 'portero', 'poder': 58},
                {'numero': '21', 'nombre': 'C. Neva', 'posicion': 'defensa', 'poder': 71},
                {'numero': '23', 'nombre': 'P. Sánchez', 'posicion': 'defensa', 'poder': 68},
                {'numero': '22', 'nombre': 'L. López', 'posicion': 'defensa', 'poder': 68},
                {'numero': '24', 'nombre': 'Vallejo', 'posicion': 'defensa', 'poder': 72},
                {'numero': '5', 'nombre': 'J. Moreno', 'posicion': 'defensa', 'poder': 64},
                {'numero': '2', 'nombre': 'Lorenzo', 'posicion': 'defensa', 'poder': 64},
                {'numero': '15', 'nombre': 'J. Germán', 'posicion': 'defensa', 'poder': 64},
                {'numero': '16', 'nombre': 'F. Gámez', 'posicion': 'defensa', 'poder': 69},
                {'numero': '3', 'nombre': 'Bernabéu', 'posicion': 'defensa', 'poder': 60},
                {'numero': '14', 'nombre': 'Jota', 'posicion': 'defensa', 'poder': 59},
                {'numero': '26', 'nombre': 'Á. Rubio', 'posicion': 'defensa', 'poder': 65},
                {'numero': '4', 'nombre': 'Agus Medina', 'posicion': 'medio', 'poder': 71},
                {'numero': '8', 'nombre': 'Pacheco', 'posicion': 'medio', 'poder': 64},
                {'numero': '6', 'nombre': 'Meléndez', 'posicion': 'medio', 'poder': 65},
                {'numero': '12', 'nombre': 'Cedeño', 'posicion': 'medio', 'poder': 66},
                {'numero': '17', 'nombre': 'M. Fernández', 'posicion': 'medio', 'poder': 69},
                {'numero': '9', 'nombre': 'Obeng', 'posicion': 'medio', 'poder': 67},
                {'numero': '11', 'nombre': 'J. Villar', 'posicion': 'medio', 'poder': 65},
                {'numero': '7', 'nombre': 'Valverde', 'posicion': 'medio', 'poder': 65},
                {'numero': '20', 'nombre': 'Capi', 'posicion': 'medio', 'poder': 61},
                {'numero': '10', 'nombre': 'Bartolomé', 'posicion': 'medio', 'poder': 65},
                {'numero': '29', 'nombre': 'Morientes', 'posicion': 'medio', 'poder': 58},
                {'numero': '27', 'nombre': 'Puertas', 'posicion': 'delantero', 'poder': 72},
                {'numero': '18', 'nombre': 'Jefté', 'posicion': 'delantero', 'poder': 70},
                {'numero': '19', 'nombre': 'Higinio', 'posicion': 'delantero', 'poder': 68},
                {'numero': '28', 'nombre': 'Lazo', 'posicion': 'delantero', 'poder': 68}],
 'Celta': [{'numero': '13', 'nombre': 'Andrei Radu', 'posicion': 'portero', 'poder': 84},
          {'numero': '25', 'nombre': 'Marc Vidal', 'posicion': 'portero', 'poder': 66},
          {'numero': '1', 'nombre': 'Iván Villar', 'posicion': 'portero', 'poder': 66},
          {'numero': '20', 'nombre': 'Marcos Alonso', 'posicion': 'defensa', 'poder': 84},
          {'numero': '2', 'nombre': 'Carl Starfelt', 'posicion': 'defensa', 'poder': 80},
          {'numero': '3', 'nombre': 'Ó. Mingueza', 'posicion': 'defensa', 'poder': 81},
          {'numero': '5', 'nombre': 'Sergio Carreira', 'posicion': 'defensa', 'poder': 80},
          {'numero': '32', 'nombre': 'Javi Rodríguez', 'posicion': 'defensa', 'poder': 79},
          {'numero': '17', 'nombre': 'Javi Rueda', 'posicion': 'defensa', 'poder': 81},
          {'numero': '14', 'nombre': 'Álvaro Núñez', 'posicion': 'defensa', 'poder': 74},
          {'numero': '24', 'nombre': 'C. Domínguez', 'posicion': 'defensa', 'poder': 72},
          {'numero': '29', 'nombre': 'Yoel Lago', 'posicion': 'defensa', 'poder': 73},
          {'numero': '12', 'nombre': 'Manu Fernández', 'posicion': 'defensa', 'poder': 74},
          {'numero': '21', 'nombre': 'Mihailo Ristić', 'posicion': 'defensa', 'poder': 73},
          {'numero': '4', 'nombre': 'Joseph Aidoo', 'posicion': 'defensa', 'poder': 75},
          {'numero': '6', 'nombre': 'Ilaix Moriba', 'posicion': 'medio', 'poder': 82},
          {'numero': '16', 'nombre': 'Miguel Román', 'posicion': 'medio', 'poder': 78},
          {'numero': '15', 'nombre': 'M. Vecino', 'posicion': 'medio', 'poder': 77},
          {'numero': '22', 'nombre': 'Hugo Sotelo', 'posicion': 'medio', 'poder': 79},
          {'numero': '8', 'nombre': 'Fer López', 'posicion': 'medio', 'poder': 78},
          {'numero': '36', 'nombre': 'Andrés Antañón', 'posicion': 'medio', 'poder': 70},
          {'numero': '38', 'nombre': 'Hugo Burcio', 'posicion': 'medio', 'poder': 66},
          {'numero': '7', 'nombre': 'Borja Iglesias', 'posicion': 'delantero', 'poder': 85},
          {'numero': '10', 'nombre': 'Iago Aspas', 'posicion': 'delantero', 'poder': 85},
          {'numero': '9', 'nombre': 'Ferran Jutglà', 'posicion': 'delantero', 'poder': 82},
          {'numero': '18', 'nombre': 'Pablo Durán', 'posicion': 'delantero', 'poder': 79},
          {'numero': '23', 'nombre': 'Hugo Álvarez', 'posicion': 'delantero', 'poder': 80},
          {'numero': '19', 'nombre': 'W. Swedberg', 'posicion': 'delantero', 'poder': 81},
          {'numero': '39', 'nombre': 'J. El-Abdellaoui', 'posicion': 'delantero', 'poder': 75},
          {'numero': '30', 'nombre': 'Hugo González', 'posicion': 'delantero', 'poder': 66},
          {'numero': '28', 'nombre': 'Angelito', 'posicion': 'delantero', 'poder': 65},
          {'numero': '11', 'nombre': 'Franco Cervi', 'posicion': 'delantero', 'poder': 78}],
 'Osasuna': [{'numero': '1', 'nombre': 'Sergio Herrera', 'posicion': 'portero', 'poder': 84},
            {'numero': '13', 'nombre': 'Aitor Fernández', 'posicion': 'portero', 'poder': 78},
            {'numero': '31', 'nombre': 'D. Stamatakis', 'posicion': 'portero', 'poder': 66},
            {'numero': '32', 'nombre': 'Rafa Fernández', 'posicion': 'portero', 'poder': 65},
            {'numero': '24', 'nombre': 'A. Catena', 'posicion': 'defensa', 'poder': 83},
            {'numero': '22', 'nombre': 'Enzo Boyomo', 'posicion': 'defensa', 'poder': 82},
            {'numero': '23', 'nombre': 'Abel Bretones', 'posicion': 'defensa', 'poder': 81},
            {'numero': '19', 'nombre': 'V. Rosier', 'posicion': 'defensa', 'poder': 81},
            {'numero': '20', 'nombre': 'Javi Galán', 'posicion': 'defensa', 'poder': 80},
            {'numero': '5', 'nombre': 'J. Herrando', 'posicion': 'defensa', 'poder': 80},
            {'numero': '3', 'nombre': 'Juan Cruz', 'posicion': 'defensa', 'poder': 78},
            {'numero': '41', 'nombre': 'Íñigo Arguibide', 'posicion': 'defensa', 'poder': 72},
            {'numero': '34', 'nombre': 'Raúl Chasco', 'posicion': 'defensa', 'poder': 65},
            {'numero': '42', 'nombre': 'M. Serrano', 'posicion': 'defensa', 'poder': 65},
            {'numero': '6', 'nombre': 'Lucas Torró', 'posicion': 'medio', 'poder': 83},
            {'numero': '10', 'nombre': 'Aimar Oroz', 'posicion': 'medio', 'poder': 84},
            {'numero': '7', 'nombre': 'J. Moncayola', 'posicion': 'medio', 'poder': 83},
            {'numero': '16', 'nombre': 'Moi Gómez', 'posicion': 'medio', 'poder': 80},
            {'numero': '8', 'nombre': 'Iker Muñoz', 'posicion': 'medio', 'poder': 79},
            {'numero': '29', 'nombre': 'A. Osambela', 'posicion': 'medio', 'poder': 77},
            {'numero': '26', 'nombre': 'M. Echegoyen', 'posicion': 'medio', 'poder': 65},
            {'numero': '17', 'nombre': 'A. Budimir', 'posicion': 'delantero', 'poder': 85},
            {'numero': '14', 'nombre': 'Rubén García', 'posicion': 'delantero', 'poder': 83},
            {'numero': '21', 'nombre': 'Víctor Muñoz', 'posicion': 'delantero', 'poder': 84},
            {'numero': '9', 'nombre': 'Raúl García', 'posicion': 'delantero', 'poder': 80},
            {'numero': '18', 'nombre': 'Raúl Moro', 'posicion': 'delantero', 'poder': 79},
            {'numero': '11', 'nombre': 'Kike Barja', 'posicion': 'delantero', 'poder': 78},
            {'numero': '2', 'nombre': 'Iker Benito', 'posicion': 'delantero', 'poder': 75},
            {'numero': '27', 'nombre': 'Martín Pedroarena', 'posicion': 'delantero', 'poder': 65}],
 'Deportivo Alavés': [{'numero': '1', 'nombre': 'Antonio Sivera', 'posicion': 'portero', 'poder': 84},
                     {'numero': '13', 'nombre': 'Raúl Fernández', 'posicion': 'portero', 'poder': 70},
                     {'numero': '31', 'nombre': 'Grégo Świderski', 'posicion': 'portero', 'poder': 66},
                     {'numero': '33', 'nombre': 'Rubén Montero', 'posicion': 'portero', 'poder': 65},
                     {'numero': '14', 'nombre': 'N. Tenaglia', 'posicion': 'defensa', 'poder': 82},
                     {'numero': '17', 'nombre': 'Jonny', 'posicion': 'defensa', 'poder': 81},
                     {'numero': '5', 'nombre': 'Jon Pacheco', 'posicion': 'defensa', 'poder': 81},
                     {'numero': '24', 'nombre': 'V. Parada', 'posicion': 'defensa', 'poder': 80},
                     {'numero': '3', 'nombre': 'Yusi Enríquez', 'posicion': 'defensa', 'poder': 79},
                     {'numero': '2', 'nombre': 'F. Garcés', 'posicion': 'defensa', 'poder': 78},
                     {'numero': '16', 'nombre': 'V. Koski', 'posicion': 'defensa', 'poder': 74},
                     {'numero': '27', 'nombre': 'Egoitz Muñoz', 'posicion': 'defensa', 'poder': 66},
                     {'numero': '35', 'nombre': 'Xanet Oláiz', 'posicion': 'defensa', 'poder': 65},
                     {'numero': '36', 'nombre': 'Paco Sanz', 'posicion': 'defensa', 'poder': 65},
                     {'numero': '30', 'nombre': 'Carlos Ballestero', 'posicion': 'defensa', 'poder': 66},
                     {'numero': '8', 'nombre': 'Antonio Blanco', 'posicion': 'medio', 'poder': 83},
                     {'numero': '19', 'nombre': 'Pablo Ibáñez', 'posicion': 'medio', 'poder': 82},
                     {'numero': '10', 'nombre': 'C. Aleñá', 'posicion': 'medio', 'poder': 82},
                     {'numero': '18', 'nombre': 'Jon Guridi', 'posicion': 'medio', 'poder': 80},
                     {'numero': '6', 'nombre': 'Ander Guevara', 'posicion': 'medio', 'poder': 79},
                     {'numero': '4', 'nombre': 'Denis Suárez', 'posicion': 'medio', 'poder': 82},
                     {'numero': '20', 'nombre': 'Calebe', 'posicion': 'medio', 'poder': 79},
                     {'numero': '23', 'nombre': 'C. Protesoni', 'posicion': 'medio', 'poder': 77},
                     {'numero': '28', 'nombre': 'L. Pinillos', 'posicion': 'medio', 'poder': 65},
                     {'numero': '11', 'nombre': 'Toni Martínez', 'posicion': 'delantero', 'poder': 84},
                     {'numero': '15', 'nombre': 'Lucas Boyé', 'posicion': 'delantero', 'poder': 83},
                     {'numero': '21', 'nombre': 'Abde Rebbach', 'posicion': 'delantero', 'poder': 81},
                     {'numero': '7', 'nombre': 'Á. Pérez', 'posicion': 'delantero', 'poder': 80},
                     {'numero': '22', 'nombre': 'I. Diabate', 'posicion': 'delantero', 'poder': 78},
                     {'numero': '9', 'nombre': 'Mariano', 'posicion': 'delantero', 'poder': 77},
                     {'numero': '34', 'nombre': 'Aitor Mañas', 'posicion': 'delantero', 'poder': 66},
                     {'numero': '29', 'nombre': 'D. Morcillo', 'posicion': 'delantero', 'poder': 65},
                     {'numero': '32', 'nombre': 'Izei Hernández', 'posicion': 'delantero', 'poder': 65}],
 'Girona': [{'numero': '13', 'nombre': 'P. Gazzaniga', 'posicion': 'portero', 'poder': 84},
           {'numero': '22', 'nombre': 'M. Ter Stegen', 'posicion': 'portero', 'poder': 88},
           {'numero': '25', 'nombre': 'V. Krapyvtsov', 'posicion': 'portero', 'poder': 78},
           {'numero': '1', 'nombre': 'Rubén Blanco', 'posicion': 'portero', 'poder': 76},
           {'numero': '43', 'nombre': 'A. Andreev', 'posicion': 'portero', 'poder': 66},
           {'numero': '17', 'nombre': 'Daley Blind', 'posicion': 'defensa', 'poder': 84},
           {'numero': '4', 'nombre': 'Arnau Martínez', 'posicion': 'defensa', 'poder': 83},
           {'numero': '12', 'nombre': 'Vitor Reis', 'posicion': 'defensa', 'poder': 82},
           {'numero': '24', 'nombre': 'Álex Moreno', 'posicion': 'defensa', 'poder': 83},
           {'numero': '2', 'nombre': 'Hugo Rincón', 'posicion': 'defensa', 'poder': 80},
           {'numero': '16', 'nombre': 'A. Francés', 'posicion': 'defensa', 'poder': 80},
           {'numero': '5', 'nombre': 'David López', 'posicion': 'defensa', 'poder': 79},
           {'numero': '31', 'nombre': 'A. Salguero', 'posicion': 'defensa', 'poder': 65},
           {'numero': '27', 'nombre': 'Pol Arnau', 'posicion': 'defensa', 'poder': 65},
           {'numero': '28', 'nombre': 'Gibi', 'posicion': 'defensa', 'poder': 65},
           {'numero': '18', 'nombre': 'A. Ounahi', 'posicion': 'medio', 'poder': 84},
           {'numero': '20', 'nombre': 'Axel Witsel', 'posicion': 'medio', 'poder': 83},
           {'numero': '23', 'nombre': 'Iván Martín', 'posicion': 'medio', 'poder': 82},
           {'numero': '11', 'nombre': 'Thomas Lemar', 'posicion': 'medio', 'poder': 83},
           {'numero': '8', 'nombre': 'Fran Beltrán', 'posicion': 'medio', 'poder': 81},
           {'numero': '14', 'nombre': 'C. Echeverri', 'posicion': 'medio', 'poder': 80},
           {'numero': '6', 'nombre': 'D. Van De Beek', 'posicion': 'medio', 'poder': 79},
           {'numero': '29', 'nombre': 'Lass', 'posicion': 'medio', 'poder': 70},
           {'numero': '36', 'nombre': 'Ricard Artero', 'posicion': 'medio', 'poder': 65},
           {'numero': '19', 'nombre': 'V. Vanat', 'posicion': 'delantero', 'poder': 85},
           {'numero': '15', 'nombre': 'V. Tsygankov', 'posicion': 'delantero', 'poder': 84},
           {'numero': '21', 'nombre': 'Bryan Gil', 'posicion': 'delantero', 'poder': 82},
           {'numero': '7', 'nombre': 'C. Stuani', 'posicion': 'delantero', 'poder': 81},
           {'numero': '3', 'nombre': 'J. Roca', 'posicion': 'delantero', 'poder': 80},
           {'numero': '8', 'nombre': 'Portu', 'posicion': 'delantero', 'poder': 79},
           {'numero': '9', 'nombre': 'Abel Ruiz', 'posicion': 'delantero', 'poder': 78},
           {'numero': '44', 'nombre': 'Papa Ba', 'posicion': 'delantero', 'poder': 65},
           {'numero': '30', 'nombre': 'Javier Sarasa', 'posicion': 'delantero', 'poder': 65},
           {'numero': '32', 'nombre': 'Juan Arango', 'posicion': 'delantero', 'poder': 66}],
 'Real Oviedo': [{'numero': '13', 'nombre': 'Aarón Escandell', 'posicion': 'portero', 'poder': 84},
                {'numero': '1', 'nombre': 'H. Moldovan', 'posicion': 'portero', 'poder': 78},
                {'numero': '26', 'nombre': 'M. Narváez', 'posicion': 'portero', 'poder': 66},
                {'numero': '22', 'nombre': 'Nacho Vidal', 'posicion': 'defensa', 'poder': 80},
                {'numero': '4', 'nombre': 'David Costas', 'posicion': 'defensa', 'poder': 80},
                {'numero': '12', 'nombre': 'Dani Calvo', 'posicion': 'defensa', 'poder': 79},
                {'numero': '16', 'nombre': 'David Carmo', 'posicion': 'defensa', 'poder': 81},
                {'numero': '3', 'nombre': 'R. Alhassane', 'posicion': 'defensa', 'poder': 79},
                {'numero': '25', 'nombre': 'Javi López', 'posicion': 'defensa', 'poder': 80},
                {'numero': '24', 'nombre': 'Lucas Ahijado', 'posicion': 'defensa', 'poder': 78},
                {'numero': '2', 'nombre': 'Eric Bailly', 'posicion': 'defensa', 'poder': 80},
                {'numero': '33', 'nombre': 'Diego Espinosa', 'posicion': 'defensa', 'poder': 65},
                {'numero': '30', 'nombre': 'Marco Esteban', 'posicion': 'defensa', 'poder': 65},
                {'numero': '29', 'nombre': 'Omar Falah', 'posicion': 'defensa', 'poder': 65},
                {'numero': '34', 'nombre': 'A. Fernández', 'posicion': 'defensa', 'poder': 65},
                {'numero': '5', 'nombre': 'A. Reina', 'posicion': 'medio', 'poder': 82},
                {'numero': '11', 'nombre': 'S. Colombatto', 'posicion': 'medio', 'poder': 81},
                {'numero': '20', 'nombre': 'L. Dendoncker', 'posicion': 'medio', 'poder': 81},
                {'numero': '6', 'nombre': 'Kwasi Sibo', 'posicion': 'medio', 'poder': 80},
                {'numero': '21', 'nombre': 'Luka Ilić', 'posicion': 'medio', 'poder': 79},
                {'numero': '8', 'nombre': 'Santi Cazorla', 'posicion': 'medio', 'poder': 82},
                {'numero': '23', 'nombre': 'N. Fonseca', 'posicion': 'medio', 'poder': 79},
                {'numero': '27', 'nombre': 'P. Agudín', 'posicion': 'medio', 'poder': 72},
                {'numero': '32', 'nombre': 'Dieguito', 'posicion': 'medio', 'poder': 65},
                {'numero': '31', 'nombre': 'Cheli', 'posicion': 'medio', 'poder': 65},
                {'numero': '9', 'nombre': 'F. Viñas', 'posicion': 'delantero', 'poder': 83},
                {'numero': '7', 'nombre': 'Ilyas Chaira', 'posicion': 'delantero', 'poder': 82},
                {'numero': '10', 'nombre': 'H. Hassan', 'posicion': 'delantero', 'poder': 81},
                {'numero': '15', 'nombre': 'Thiago Fernández', 'posicion': 'delantero', 'poder': 80},
                {'numero': '19', 'nombre': 'Álex Forés', 'posicion': 'delantero', 'poder': 78},
                {'numero': '14', 'nombre': 'Ovie', 'posicion': 'delantero', 'poder': 75},
                {'numero': '17', 'nombre': 'T. Borbas', 'posicion': 'delantero', 'poder': 74},
                {'numero': '28', 'nombre': 'Lamine Gueye', 'posicion': 'delantero', 'poder': 65},
                {'numero': '17', 'nombre': 'B. Dominguès', 'posicion': 'delantero', 'poder': 65}],
 'Levante': [{'numero': '13', 'nombre': 'M. Ryan', 'posicion': 'portero', 'poder': 84},
            {'numero': '1', 'nombre': 'Pablo Cuñat', 'posicion': 'portero', 'poder': 78},
            {'numero': '32', 'nombre': 'A. Primo', 'posicion': 'portero', 'poder': 66},
            {'numero': '34', 'nombre': 'Caye Romero', 'posicion': 'portero', 'poder': 65},
            {'numero': '4', 'nombre': 'Dela', 'posicion': 'defensa', 'poder': 81},
            {'numero': '23', 'nombre': 'Manu Sánchez', 'posicion': 'defensa', 'poder': 82},
            {'numero': '22', 'nombre': 'Jeremy Toljan', 'posicion': 'defensa', 'poder': 82},
            {'numero': '2', 'nombre': 'M. Moreno', 'posicion': 'defensa', 'poder': 80},
            {'numero': '17', 'nombre': 'Víctor García', 'posicion': 'defensa', 'poder': 79},
            {'numero': '3', 'nombre': 'Alan Matturro', 'posicion': 'defensa', 'poder': 79},
            {'numero': '5', 'nombre': 'U. Elgezabal', 'posicion': 'defensa', 'poder': 78},
            {'numero': '6', 'nombre': 'Diego Pampín', 'posicion': 'defensa', 'poder': 76},
            {'numero': '29', 'nombre': 'Nacho Pérez', 'posicion': 'defensa', 'poder': 72},
            {'numero': '28', 'nombre': 'Martín Krug', 'posicion': 'defensa', 'poder': 65},
            {'numero': '35', 'nombre': 'H. Nakoha', 'posicion': 'defensa', 'poder': 65},
            {'numero': '24', 'nombre': 'Carlos Álvarez', 'posicion': 'medio', 'poder': 83},
            {'numero': '10', 'nombre': 'Pablo Martínez', 'posicion': 'medio', 'poder': 82},
            {'numero': '20', 'nombre': 'Oriol Rey', 'posicion': 'medio', 'poder': 80},
            {'numero': '16', 'nombre': 'K. Arriaga', 'posicion': 'medio', 'poder': 81},
            {'numero': '12', 'nombre': 'Unai Vencedor', 'posicion': 'medio', 'poder': 80},
            {'numero': '8', 'nombre': 'Olasagasti', 'posicion': 'medio', 'poder': 82},
            {'numero': '18', 'nombre': 'Iker Losada', 'posicion': 'medio', 'poder': 80},
            {'numero': '14', 'nombre': 'U. Raghouber', 'posicion': 'medio', 'poder': 78},
            {'numero': '33', 'nombre': 'Joan Ruiz', 'posicion': 'medio', 'poder': 65},
            {'numero': '19', 'nombre': 'Carlos Espí', 'posicion': 'delantero', 'poder': 83},
            {'numero': '9', 'nombre': 'Iván Romero', 'posicion': 'delantero', 'poder': 82},
            {'numero': '21', 'nombre': 'Etta Eyong', 'posicion': 'delantero', 'poder': 81},
            {'numero': '7', 'nombre': 'Roger Brugué', 'posicion': 'delantero', 'poder': 80},
            {'numero': '26', 'nombre': 'Kareem Tunde', 'posicion': 'delantero', 'poder': 79},
            {'numero': '11', 'nombre': 'Morales', 'posicion': 'delantero', 'poder': 78},
            {'numero': '27', 'nombre': 'Paco Cortés', 'posicion': 'delantero', 'poder': 75},
            {'numero': '55', 'nombre': 'T. Abed', 'posicion': 'delantero', 'poder': 66},
            {'numero': '37', 'nombre': 'D. Cervera', 'posicion': 'delantero', 'poder': 65}],
 'Mallorca': [{'numero': '1', 'nombre': 'Leo Román', 'posicion': 'portero', 'poder': 84},
             {'numero': '13', 'nombre': 'L. Bergström', 'posicion': 'portero', 'poder': 78},
             {'numero': '38', 'nombre': 'Nil', 'posicion': 'portero', 'poder': 66},
             {'numero': '25', 'nombre': 'I. Cuéllar', 'posicion': 'portero', 'poder': 66},
             {'numero': '42', 'nombre': 'Rareș Vlad', 'posicion': 'portero', 'poder': 65},
             {'numero': '22', 'nombre': 'Johan Mojica', 'posicion': 'defensa', 'poder': 82},
             {'numero': '24', 'nombre': 'Martin Valjent', 'posicion': 'defensa', 'poder': 83},
             {'numero': '23', 'nombre': 'Pablo Maffeo', 'posicion': 'defensa', 'poder': 82},
             {'numero': '21', 'nombre': 'A. Raíllo', 'posicion': 'defensa', 'poder': 81},
             {'numero': '4', 'nombre': 'M. Kumbulla', 'posicion': 'defensa', 'poder': 80},
             {'numero': '27', 'nombre': 'David López', 'posicion': 'defensa', 'poder': 79},
             {'numero': '3', 'nombre': 'Toni Lato', 'posicion': 'defensa', 'poder': 78},
             {'numero': '2', 'nombre': 'Mateu Morey', 'posicion': 'defensa', 'poder': 79},
             {'numero': '29', 'nombre': 'L. Orejuela', 'posicion': 'defensa', 'poder': 72},
             {'numero': '44', 'nombre': 'M. Calatayud', 'posicion': 'defensa', 'poder': 66},
             {'numero': '26', 'nombre': 'Iliesse Salhi', 'posicion': 'defensa', 'poder': 65},
             {'numero': '34', 'nombre': 'J. Olaizola', 'posicion': 'defensa', 'poder': 65},
             {'numero': '32', 'nombre': 'Leo Sánchez', 'posicion': 'defensa', 'poder': 65},
             {'numero': '10', 'nombre': 'Sergi Darder', 'posicion': 'medio', 'poder': 85},
             {'numero': '12', 'nombre': 'Samu Costa', 'posicion': 'medio', 'poder': 83},
             {'numero': '5', 'nombre': 'Omar Mascarell', 'posicion': 'medio', 'poder': 82},
             {'numero': '8', 'nombre': 'Manu Morlanes', 'posicion': 'medio', 'poder': 81},
             {'numero': '20', 'nombre': 'Pablo Torre', 'posicion': 'medio', 'poder': 82},
             {'numero': '6', 'nombre': 'Antonio Sánchez', 'posicion': 'medio', 'poder': 79},
             {'numero': '28', 'nombre': 'Cesc Riba', 'posicion': 'medio', 'poder': 65},
             {'numero': '41', 'nombre': 'Jan Salas', 'posicion': 'medio', 'poder': 66},
             {'numero': '39', 'nombre': 'Jandro', 'posicion': 'medio', 'poder': 65},
             {'numero': '7', 'nombre': 'Vedat Muriqi', 'posicion': 'delantero', 'poder': 87},
             {'numero': '17', 'nombre': 'Jan Virgili', 'posicion': 'delantero', 'poder': 81},
             {'numero': '18', 'nombre': 'Mateo Joseph', 'posicion': 'delantero', 'poder': 81},
             {'numero': '11', 'nombre': 'Takuma Asano', 'posicion': 'delantero', 'poder': 80},
             {'numero': '15', 'nombre': 'Z. Luvumbo', 'posicion': 'delantero', 'poder': 79},
             {'numero': '9', 'nombre': 'Abdón Prats', 'posicion': 'delantero', 'poder': 78},
             {'numero': '19', 'nombre': 'Javi Llabrés', 'posicion': 'delantero', 'poder': 77},
             {'numero': '30', 'nombre': 'Justin Kalumba', 'posicion': 'delantero', 'poder': 72}],
 'Elche': [{'numero': '1', 'nombre': 'M. Dituro', 'posicion': 'portero', 'poder': 83},
          {'numero': '13', 'nombre': 'Iñaki Peña', 'posicion': 'portero', 'poder': 83},
          {'numero': '45', 'nombre': 'A. Iturbe', 'posicion': 'portero', 'poder': 66},
          {'numero': '22', 'nombre': 'David Affengruber', 'posicion': 'defensa', 'poder': 81},
          {'numero': '23', 'nombre': 'Víctor Chust', 'posicion': 'defensa', 'poder': 80},
          {'numero': '6', 'nombre': 'P. Bigas', 'posicion': 'defensa', 'poder': 81},
          {'numero': '3', 'nombre': 'Adrià Pedrosa', 'posicion': 'defensa', 'poder': 80},
          {'numero': '21', 'nombre': 'L. Pétrot', 'posicion': 'defensa', 'poder': 80},
          {'numero': '18', 'nombre': 'John Chetauya', 'posicion': 'defensa', 'poder': 78},
          {'numero': '39', 'nombre': 'Héctor Fort', 'posicion': 'defensa', 'poder': 79},
          {'numero': '42', 'nombre': 'Buba Sangaré', 'posicion': 'defensa', 'poder': 77},
          {'numero': '26', 'nombre': 'B. Sina', 'posicion': 'defensa', 'poder': 65},
          {'numero': '33', 'nombre': 'Pablo Felipe', 'posicion': 'defensa', 'poder': 65},
          {'numero': '36', 'nombre': 'N. Salvador', 'posicion': 'defensa', 'poder': 65},
          {'numero': '31', 'nombre': 'D. Delgado', 'posicion': 'defensa', 'poder': 65},
          {'numero': '27', 'nombre': 'A. Niculăesei', 'posicion': 'defensa', 'poder': 65},
          {'numero': '43', 'nombre': 'A. Herráiz', 'posicion': 'defensa', 'poder': 65},
          {'numero': '14', 'nombre': 'Aleix Febas', 'posicion': 'medio', 'poder': 84},
          {'numero': '8', 'nombre': 'Marc Aguado', 'posicion': 'medio', 'poder': 82},
          {'numero': '16', 'nombre': 'Martim Neto', 'posicion': 'medio', 'poder': 82},
          {'numero': '12', 'nombre': 'Gonzalo Villar', 'posicion': 'medio', 'poder': 80},
          {'numero': '5', 'nombre': 'F. Redondo', 'posicion': 'medio', 'poder': 78},
          {'numero': '32', 'nombre': 'Adam Boayar', 'posicion': 'medio', 'poder': 72},
          {'numero': '37', 'nombre': 'A. Martínez', 'posicion': 'medio', 'poder': 65},
          {'numero': '9', 'nombre': 'André Da Silva', 'posicion': 'delantero', 'poder': 84},
          {'numero': '10', 'nombre': 'Rafa Mir', 'posicion': 'delantero', 'poder': 83},
          {'numero': '11', 'nombre': 'Germán Valera', 'posicion': 'delantero', 'poder': 82},
          {'numero': '20', 'nombre': 'Álvaro Rodríguez', 'posicion': 'delantero', 'poder': 82},
          {'numero': '19', 'nombre': 'G. Diangana', 'posicion': 'delantero', 'poder': 81},
          {'numero': '15', 'nombre': 'Tete Morente', 'posicion': 'delantero', 'poder': 80},
          {'numero': '17', 'nombre': 'Josan', 'posicion': 'delantero', 'poder': 79},
          {'numero': '7', 'nombre': 'Yago Santiago', 'posicion': 'delantero', 'poder': 77},
          {'numero': '24', 'nombre': 'L. Cepeda', 'posicion': 'delantero', 'poder': 76},
          {'numero': '29', 'nombre': 'Piri', 'posicion': 'delantero', 'poder': 65},
          {'numero': '38', 'nombre': 'Álex Sánchez', 'posicion': 'delantero', 'poder': 66},
          {'numero': '46', 'nombre': 'Juan Piera', 'posicion': 'delantero', 'poder': 65}],
 'Valencia': [{'numero': '25', 'nombre': 'J. Agirrezabala', 'posicion': 'portero', 'poder': 83},
             {'numero': '1', 'nombre': 'S. Dimitrievski', 'posicion': 'portero', 'poder': 83},
             {'numero': '28', 'nombre': 'Vicent Abril', 'posicion': 'portero', 'poder': 66},
             {'numero': '41', 'nombre': 'Pere García', 'posicion': 'portero', 'poder': 65},
             {'numero': '13', 'nombre': 'Cristian Rivero', 'posicion': 'portero', 'poder': 66},
             {'numero': '14', 'nombre': 'José Gayà', 'posicion': 'defensa', 'poder': 85},
             {'numero': '5', 'nombre': 'César Tárrega', 'posicion': 'defensa', 'poder': 80},
             {'numero': '20', 'nombre': 'D. Foulquier', 'posicion': 'defensa', 'poder': 79},
             {'numero': '4', 'nombre': 'M. Diakhaby', 'posicion': 'defensa', 'poder': 80},
             {'numero': '12', 'nombre': 'Thierry Correia', 'posicion': 'defensa', 'poder': 80},
             {'numero': '4', 'nombre': 'Unai Núñez', 'posicion': 'defensa', 'poder': 79},
             {'numero': '3', 'nombre': 'Copete', 'posicion': 'defensa', 'poder': 80},
             {'numero': '24', 'nombre': 'Eray Cömert', 'posicion': 'defensa', 'poder': 81},
             {'numero': '21', 'nombre': 'Jesús Vázquez', 'posicion': 'defensa', 'poder': 78},
             {'numero': '26', 'nombre': 'Rubo', 'posicion': 'defensa', 'poder': 66},
             {'numero': '36', 'nombre': 'Marcos Navarro', 'posicion': 'defensa', 'poder': 65},
             {'numero': '32', 'nombre': 'A. Panach', 'posicion': 'defensa', 'poder': 65},
             {'numero': '40', 'nombre': 'J. Fontanet', 'posicion': 'defensa', 'poder': 65},
             {'numero': '8', 'nombre': 'Javi Guerra', 'posicion': 'medio', 'poder': 85},
             {'numero': '23', 'nombre': 'Filip Ugrinić', 'posicion': 'medio', 'poder': 81},
             {'numero': '18', 'nombre': 'Pepelu', 'posicion': 'medio', 'poder': 83},
             {'numero': '19', 'nombre': 'Dani Raba', 'posicion': 'medio', 'poder': 77},
             {'numero': '10', 'nombre': 'André Almeida', 'posicion': 'medio', 'poder': 80},
             {'numero': '2', 'nombre': 'Guido Rodríguez', 'posicion': 'medio', 'poder': 83},
             {'numero': '22', 'nombre': 'B. Santamaria', 'posicion': 'medio', 'poder': 78},
             {'numero': '29', 'nombre': 'Lucas Núñez', 'posicion': 'medio', 'poder': 65},
             {'numero': '42', 'nombre': 'Aaron Mayol', 'posicion': 'medio', 'poder': 65},
             {'numero': '9', 'nombre': 'Hugo Duro', 'posicion': 'delantero', 'poder': 84},
             {'numero': '16', 'nombre': 'Diego López', 'posicion': 'delantero', 'poder': 82},
             {'numero': '11', 'nombre': 'Luis Rioja', 'posicion': 'delantero', 'poder': 83},
             {'numero': '15', 'nombre': 'Lucas Beltrán', 'posicion': 'delantero', 'poder': 82},
             {'numero': '7', 'nombre': 'A. Danjuma', 'posicion': 'delantero', 'poder': 83},
             {'numero': '6', 'nombre': 'Umar Sadiq', 'posicion': 'delantero', 'poder': 80},
             {'numero': '17', 'nombre': 'L. Ramazani', 'posicion': 'delantero', 'poder': 81},
             {'numero': '37', 'nombre': 'A. Blázquez', 'posicion': 'delantero', 'poder': 65},
             {'numero': '27', 'nombre': 'David Otorbi', 'posicion': 'delantero', 'poder': 65}],
 'Rayo Vallecano': [{'numero': '13', 'nombre': 'A. Batalla', 'posicion': 'portero', 'poder': 83},
                   {'numero': '1', 'nombre': 'Dani Cárdenas', 'posicion': 'portero', 'poder': 80},
                   {'numero': '30', 'nombre': 'Juanpe', 'posicion': 'portero', 'poder': 66},
                   {'numero': '40', 'nombre': 'Adrián Molina', 'posicion': 'portero', 'poder': 65},
                   {'numero': '2', 'nombre': 'Andrei Rațiu', 'posicion': 'defensa', 'poder': 81},
                   {'numero': '24', 'nombre': 'Florian Lejeune', 'posicion': 'defensa', 'poder': 83},
                   {'numero': '3', 'nombre': 'Pep Chavarría', 'posicion': 'defensa', 'poder': 80},
                   {'numero': '22', 'nombre': 'Pacha Espino', 'posicion': 'defensa', 'poder': 80},
                   {'numero': '20', 'nombre': 'Iván Balliu', 'posicion': 'defensa', 'poder': 78},
                   {'numero': '32', 'nombre': 'Nobel Mendy', 'posicion': 'defensa', 'poder': 79},
                   {'numero': '5', 'nombre': 'Luiz Felipe', 'posicion': 'defensa', 'poder': 79},
                   {'numero': '16', 'nombre': 'Abdul Mumin', 'posicion': 'defensa', 'poder': 74},
                   {'numero': '33', 'nombre': 'J. Vertrouwd', 'posicion': 'defensa', 'poder': 73},
                   {'numero': '26', 'nombre': 'Marco De Las Sías', 'posicion': 'defensa', 'poder': 65},
                   {'numero': '7', 'nombre': 'Isi Palazón', 'posicion': 'medio', 'poder': 85},
                   {'numero': '6', 'nombre': 'Pathé Ciss', 'posicion': 'medio', 'poder': 82},
                   {'numero': '17', 'nombre': 'Unai López', 'posicion': 'medio', 'poder': 81},
                   {'numero': '23', 'nombre': 'Óscar Valentín', 'posicion': 'medio', 'poder': 82},
                   {'numero': '4', 'nombre': 'Pedro Díaz', 'posicion': 'medio', 'poder': 80},
                   {'numero': '15', 'nombre': 'G. Gumbau', 'posicion': 'medio', 'poder': 79},
                   {'numero': '11', 'nombre': 'Randy Nteka', 'posicion': 'medio', 'poder': 78},
                   {'numero': '8', 'nombre': 'Óscar Trejo', 'posicion': 'medio', 'poder': 80},
                   {'numero': '28', 'nombre': 'Samu Becerra', 'posicion': 'medio', 'poder': 66},
                   {'numero': '19', 'nombre': 'Jorge De Frutos', 'posicion': 'delantero', 'poder': 85},
                   {'numero': '18', 'nombre': 'Álvaro García', 'posicion': 'delantero', 'poder': 83},
                   {'numero': '9', 'nombre': 'Alemão', 'posicion': 'delantero', 'poder': 80},
                   {'numero': '21', 'nombre': 'Fran Pérez', 'posicion': 'delantero', 'poder': 79},
                   {'numero': '10', 'nombre': 'Sergio Camello', 'posicion': 'delantero', 'poder': 78},
                   {'numero': '14', 'nombre': 'Carlos Martín', 'posicion': 'delantero', 'poder': 77},
                   {'numero': '12', 'nombre': 'Ilias Akhomach', 'posicion': 'delantero', 'poder': 79}],
 'Córdoba': [{'numero': '1', 'nombre': 'F. Palatsí', 'posicion': 'portero', 'poder': 75},
            {'numero': '13', 'nombre': 'T. Fernández', 'posicion': 'portero', 'poder': 70},
            {'numero': '2', 'nombre': 'L. Calderón', 'posicion': 'defensa', 'poder': 74},
            {'numero': '5', 'nombre': 'M. Valenzuela', 'posicion': 'defensa', 'poder': 73},
            {'numero': '6', 'nombre': 'P. Gutiérrez', 'posicion': 'defensa', 'poder': 74},
            {'numero': '3', 'nombre': 'A. Baidoo', 'posicion': 'defensa', 'poder': 73},
            {'numero': '22', 'nombre': 'C. Ángel', 'posicion': 'defensa', 'poder': 72},
            {'numero': '14', 'nombre': 'C. Boselli', 'posicion': 'defensa', 'poder': 72},
            {'numero': '23', 'nombre': 'A. Lolo', 'posicion': 'defensa', 'poder': 70},
            {'numero': '4', 'nombre': 'A. Romero', 'posicion': 'medio', 'poder': 75},
            {'numero': '8', 'nombre': 'J. Andrés Prieto', 'posicion': 'medio', 'poder': 74},
            {'numero': '10', 'nombre': 'A. Carvalho', 'posicion': 'medio', 'poder': 76},
            {'numero': '20', 'nombre': 'A. Vallejo', 'posicion': 'medio', 'poder': 74},
            {'numero': '7', 'nombre': 'C. Isidoro', 'posicion': 'medio', 'poder': 74},
            {'numero': '17', 'nombre': 'L. Arezo', 'posicion': 'medio', 'poder': 73},
            {'numero': '11', 'nombre': 'K. Mfulu', 'posicion': 'medio', 'poder': 72},
            {'numero': '16', 'nombre': 'C. Bañuls', 'posicion': 'medio', 'poder': 72},
            {'numero': '9', 'nombre': 'C. Zaldua', 'posicion': 'delantero', 'poder': 76},
            {'numero': '19', 'nombre': 'J. Sebas Moyano', 'posicion': 'delantero', 'poder': 74},
            {'numero': '21', 'nombre': 'A. Cruz', 'posicion': 'delantero', 'poder': 73},
            {'numero': '18', 'nombre': 'D. Casado', 'posicion': 'delantero', 'poder': 72}],
 'Racing': [{'numero': '1', 'nombre': 'Jokin Ezkieta', 'posicion': 'portero', 'poder': 74},
           {'numero': '13', 'nombre': 'S. Eriksson', 'posicion': 'portero', 'poder': 72},
           {'numero': '31', 'nombre': 'Álvaro Jiménez', 'posicion': 'portero', 'poder': 66},
           {'numero': '35', 'nombre': 'Laro Gómez', 'posicion': 'portero', 'poder': 66},
           {'numero': '2', 'nombre': 'Mantilla', 'posicion': 'defensa', 'poder': 75},
           {'numero': '15', 'nombre': 'Marco Sangalli', 'posicion': 'defensa', 'poder': 74},
           {'numero': '4', 'nombre': 'Manu Hernando', 'posicion': 'defensa', 'poder': 74},
           {'numero': '32', 'nombre': 'J. Salinas', 'posicion': 'defensa', 'poder': 73},
           {'numero': '21', 'nombre': 'Pablo Ramón', 'posicion': 'defensa', 'poder': 73},
           {'numero': '16', 'nombre': 'Facu González', 'posicion': 'defensa', 'poder': 72},
           {'numero': '5', 'nombre': 'Javi Castro', 'posicion': 'defensa', 'poder': 72},
           {'numero': '3', 'nombre': 'Mario García', 'posicion': 'defensa', 'poder': 71},
           {'numero': '37', 'nombre': 'A. Crespo', 'posicion': 'defensa', 'poder': 65},
           {'numero': '33', 'nombre': 'Samuel Calera', 'posicion': 'defensa', 'poder': 65},
           {'numero': '46', 'nombre': 'C. Sánchez', 'posicion': 'defensa', 'poder': 65},
           {'numero': '18', 'nombre': 'Peio Canales', 'posicion': 'medio', 'poder': 75},
           {'numero': '19', 'nombre': 'Gustavo Puerta', 'posicion': 'medio', 'poder': 75},
           {'numero': '14', 'nombre': 'Maguette Gueye', 'posicion': 'medio', 'poder': 74},
           {'numero': '8', 'nombre': 'Aritz Aldasoro', 'posicion': 'medio', 'poder': 73},
           {'numero': '23', 'nombre': 'Damián', 'posicion': 'medio', 'poder': 72},
           {'numero': '6', 'nombre': 'Í. Sainz-Maza', 'posicion': 'medio', 'poder': 71},
           {'numero': '36', 'nombre': 'S. Martínez', 'posicion': 'medio', 'poder': 69},
           {'numero': '34', 'nombre': 'D. Díaz', 'posicion': 'medio', 'poder': 65},
           {'numero': '44', 'nombre': 'Diego Fuentes', 'posicion': 'medio', 'poder': 66},
           {'numero': '11', 'nombre': 'Andrés Martín', 'posicion': 'delantero', 'poder': 77},
           {'numero': '10', 'nombre': 'Íñigo Vicente', 'posicion': 'delantero', 'poder': 76},
           {'numero': '12', 'nombre': 'Asier Villalibre', 'posicion': 'delantero', 'poder': 75},
           {'numero': '7', 'nombre': 'G. Guliashvili', 'posicion': 'delantero', 'poder': 73},
           {'numero': '20', 'nombre': 'Suleiman', 'posicion': 'delantero', 'poder': 71},
           {'numero': '9', 'nombre': 'Arana', 'posicion': 'delantero', 'poder': 69},
           {'numero': '17', 'nombre': 'J. Mata', 'posicion': 'delantero', 'poder': 70},
           {'numero': '27', 'nombre': 'Manex Lozano', 'posicion': 'delantero', 'poder': 68},
           {'numero': '43', 'nombre': 'Santi Franco', 'posicion': 'delantero', 'poder': 68}],
 'Liverpool': [{'numero': '1', 'nombre': 'Alisson', 'posicion': 'portero', 'poder': 90},
              {'numero': '25', 'nombre': 'G. Mamardashvili', 'posicion': 'portero', 'poder': 86},
              {'numero': '28', 'nombre': 'F. Woodman', 'posicion': 'portero', 'poder': 75},
              {'numero': '4', 'nombre': 'V. Van Dijk', 'posicion': 'defensa', 'poder': 89},
              {'numero': '5', 'nombre': 'I. Konaté', 'posicion': 'defensa', 'poder': 86},
              {'numero': '30', 'nombre': 'J. Frimpong', 'posicion': 'defensa', 'poder': 85},
              {'numero': '6', 'nombre': 'Miloš Kerkez', 'posicion': 'defensa', 'poder': 84},
              {'numero': '26', 'nombre': 'A. Robertson', 'posicion': 'defensa', 'poder': 85},
              {'numero': '12', 'nombre': 'Conor Bradley', 'posicion': 'defensa', 'poder': 82},
              {'numero': '2', 'nombre': 'Joe Gomez', 'posicion': 'defensa', 'poder': 81},
              {'numero': '8', 'nombre': 'D. Szoboszlai', 'posicion': 'medio', 'poder': 88},
              {'numero': '7', 'nombre': 'Florian Wirtz', 'posicion': 'medio', 'poder': 88},
              {'numero': '10', 'nombre': 'A. Mac Allister', 'posicion': 'medio', 'poder': 87},
              {'numero': '38', 'nombre': 'R. Gravenberch', 'posicion': 'medio', 'poder': 85},
              {'numero': '17', 'nombre': 'Curtis Jones', 'posicion': 'medio', 'poder': 83},
              {'numero': '3', 'nombre': 'Wataru Endo', 'posicion': 'medio', 'poder': 81},
              {'numero': '11', 'nombre': 'M. Salah', 'posicion': 'delantero', 'poder': 89},
              {'numero': '22', 'nombre': 'Hugo Ekitiké', 'posicion': 'delantero', 'poder': 87},
              {'numero': '18', 'nombre': 'Cody Gakpo', 'posicion': 'delantero', 'poder': 85},
              {'numero': '9', 'nombre': 'Alexander Isak', 'posicion': 'delantero', 'poder': 86},
              {'numero': '14', 'nombre': 'F. Chiesa', 'posicion': 'delantero', 'poder': 84},
              {'numero': '73', 'nombre': 'Rio Ngumoha', 'posicion': 'delantero', 'poder': 77}],
 'Arsenal': [{'numero': '1', 'nombre': 'David Raya', 'posicion': 'portero', 'poder': 86},
            {'numero': '13', 'nombre': 'Kepa', 'posicion': 'portero', 'poder': 82},
            {'numero': '2', 'nombre': 'W. Saliba', 'posicion': 'defensa', 'poder': 87},
            {'numero': '6', 'nombre': 'Gabriel Magalhães', 'posicion': 'defensa', 'poder': 86},
            {'numero': '12', 'nombre': 'Jurriën Timber', 'posicion': 'defensa', 'poder': 85},
            {'numero': '33', 'nombre': 'R. Calafiori', 'posicion': 'defensa', 'poder': 84},
            {'numero': '5', 'nombre': 'P. Hincapié', 'posicion': 'defensa', 'poder': 84},
            {'numero': '4', 'nombre': 'Ben White', 'posicion': 'defensa', 'poder': 83},
            {'numero': '3', 'nombre': 'C. Mosquera', 'posicion': 'defensa', 'poder': 79},
            {'numero': '49', 'nombre': 'Lewis-Skelly', 'posicion': 'defensa', 'poder': 77},
            {'numero': '89', 'nombre': 'M. Salmon', 'posicion': 'defensa', 'poder': 65},
            {'numero': '41', 'nombre': 'Declan Rice', 'posicion': 'medio', 'poder': 88},
            {'numero': '36', 'nombre': 'M. Zubimendi', 'posicion': 'medio', 'poder': 87},
            {'numero': '8', 'nombre': 'M. Ødegaard', 'posicion': 'medio', 'poder': 87},
            {'numero': '10', 'nombre': 'E. Eze', 'posicion': 'medio', 'poder': 86},
            {'numero': '23', 'nombre': 'Mikel Merino', 'posicion': 'medio', 'poder': 85},
            {'numero': '16', 'nombre': 'C. Nørgaard', 'posicion': 'medio', 'poder': 80},
            {'numero': '7', 'nombre': 'Bukayo Saka', 'posicion': 'delantero', 'poder': 88},
            {'numero': '14', 'nombre': 'V. Gyökeres', 'posicion': 'delantero', 'poder': 88},
            {'numero': '19', 'nombre': 'L. Trossard', 'posicion': 'delantero', 'poder': 85},
            {'numero': '11', 'nombre': 'Martinelli', 'posicion': 'delantero', 'poder': 84},
            {'numero': '20', 'nombre': 'Noni Madueke', 'posicion': 'delantero', 'poder': 83},
            {'numero': '29', 'nombre': 'Kai Havertz', 'posicion': 'delantero', 'poder': 83},
            {'numero': '9', 'nombre': 'Gabriel Jesus', 'posicion': 'delantero', 'poder': 82},
            {'numero': '56', 'nombre': 'M. Dowman', 'posicion': 'delantero', 'poder': 70},
            {'numero': '71', 'nombre': 'A. Harriman-Annous', 'posicion': 'delantero', 'poder': 65}]}
